name: Sign Firefox Extension

on:
  push:
    branches: [ main ]

jobs:
  sign-extension:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/Jod'
        
    - name: Install dependencies
      run: |
        npm install
        npm install -g web-ext
        
    - name: Sign Firefox extension
      run: |
        web-ext sign \
          --api-key ${{ secrets.AMO_API_KEY }} \
          --api-secret ${{ secrets.AMO_API_SECRET }} \
          --channel listed \
          --amo-metadata amo_metadata.json